easy_admin:
    site_name: 'Auto Rent -  <b>Espace Admin</b>'
    design:
      
      brand_color: '#DA251D'
    list:
        batch_actions: [{ name: 'delete', ask_confirm: true }]
        
        actions:
            # Personnalisation des icons
            - { name: 'edit', icon: 'pencil', label: false, title: 'edit' }
            - { name: 'delete', icon: 'trash', label: false, title: 'supprimer' }
    
    user:
        display_name: true
        display_avatar: false
    entities:
        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
              title: "Liste des utilisateurs"  
              fields:
                  - id
                  - firstname
                  - name
                  - phone
                  - {property: 'password', label: 'Mot de passe', type: text}
                  - email
                  - { property: 'roles', label: 'Rôles', type: json_array}
            form:
              fields:
                  - email
                  - password
                  - name
                  - firstname
                  - phone
                  - { property: 'roles', label: 'Rôles', type: choice, type_options: {expanded: true, multiple: true, choices: {'Utilisateur':'ROLE_USER', 'Administrateur':'ROLE_ADMIN'}}}
        Booking:
            class: App\Entity\Booking
            label: 'Reservations'
            list:
              title: "Liste des reservations"
              fields:
                  - PickLocation
                  - PickDate
                  - ReturnDate
                  - Car
                  - {property: 'user', label: 'Client'}
            form:
              fields:
                  - PickLocation
                  - PickDate
                  - ReturnDate
                  -  Car
                  - {property: 'user', label: 'Client'}
        Car:
            class: App\Entity\Car
            label: 'Voitures'
            list:
              title: "Liste des Voitures"
              fields:
                  - brand
                  - year
                  - price
                  - { property: 'image', type: 'image', base_path: '%app.path.car_images%' }
                  - seats
                  - transmission
                  - isNew
            form:
              fields:
                  - brand
                  - year
                  - price
                  - { property: 'imageFile', type: 'vich_image', base_path: '%app.path.car_images%' }
                  - seats
                  - transmission
                  - isNew
        #     class: App\Entity\Menu
        #     label: 'Menus'
        #     list:
        #       title: "Liste des menus proposés"
        #       fields:
        #           - entree
        #           - plat
        #           - dessert
        #           - { property: 'image', type: 'image', base_path: '%app.path.chef_images%' }
        #     form:
        #       fields:
        #           - entree
        #           - plat
        #           - dessert
        #           - { property: 'imageFile', type: 'vich_image', base_path: '%app.path.chef_images%' }
        # Commentaire:
        #     class: App\Entity\Commentaire
        #     label: 'Commentaires'
        #     list:
        #       title: "Liste des commentaires"
        #       fields:
        #           - {property: 'email', label: 'Client'}
        #           - titre
        #           - message
        #     form:
        #       fields:
        #           - {property: 'email', label: 'Client'}
        #           - titre
        #           - message
        
